name: Reusable Python Workflow

description: >
  A reusable workflow to set up Python, install dependencies, run the app, and optionally create a PR.

on:
  workflow_call:
    inputs:
      create-pr:
        required: false
        type: boolean
        default: false
      pr-base:
        required: false
        type: string
        default: 'main'
      pr-head:
        required: false
        type: string
        default: 'auto-pr-branch'
      pr-title:
        required: false
        type: string
        default: 'Automated PR from reusable workflow'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application
        run: |
          python src/main.py

      - name: Create Pull Request (optional)
        if: ${{ inputs.create-pr }}
        uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ inputs.pr-base }}
          branch: ${{ inputs.pr-head }}
          title: ${{ inputs.pr-title }}
          commit-message: ${{ inputs.pr-title }}
          body: 'This PR was created automatically by the reusable workflow.'